
services:
  postgres:
    image: postgres:16.9-bookworm
    container_name: postgres-dev
    restart: always
    ports:
      - '${DOCKER_PORT}:5432'
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

volumes:
  pgdata-dev:
   name: pgdata-dev
