services:
  app:
    container_name: backend-app
    build:
      context: .
      target: development
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "pnpm prisma migrate deploy &&
             pnpm prisma generate &&
             pnpm run start:dev"

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
