services:
  postgres-test:
    image: postgres:16.9-bookworm
    container_name: postgres-test
    restart: always
    ports:
      - '${DOCKER_PORT}:5432'
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-test:/var/lib/postgresql/data

volumes:
  pgdata-test:
    name: pgdata-test
