name: Bug Report
description: Report a reproducible bug in the application.
title: "[Bug] "
labels: ["type: bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following information to help us investigate.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What browser, device, or system did you use?
      placeholder: "e.g., Chrome 124 on Windows 10"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "It should have..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, it..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Attach screenshots or logs if applicable.
      placeholder: "You can drag images here or paste logs."

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I've checked for existing issues related to this bug.
          required: true
        - label: I've filled in all required fields.
          required: true
