name: Feature Request
description: Propose a new feature or improvement.
title: "[Feature] "
labels: ["type: feature", "triage"]
projects: ["Frontend", "Backend"]
assignees: "SampleAssignee"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What is the feature or improvement?
      placeholder: "e.g., Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Problem
      description: What problem does this solve or what use case does it support?
      placeholder: "Users need this because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you imagine the feature working.
      placeholder: "Add a toggle in settings..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?
      placeholder: "We also considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High – needed for current milestone
        - Medium – nice to have soon
        - Low – no urgency
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched for existing feature requests.
          required: true
